### ISSUE TITLE
Selftest and Feed Generation slowdown with MySQL 8 / MariaDB 10.4

### ISSUE THREAD

**Issue by batmike** [magmodules/magento2-channable#104]
I've been talking with the support email about this but wanted to bring it up here to see if there was any other feedback.

There’s a issue at https://bugs.mysql.com/bug.php?id=97709 and the second to last comment mentions that including a WHERE id > 0 makes SELECT COUNT queries work with execution timing more like SQL 5.7 (or comparable MariaDB versions).

After adding a filter to the product collection in the Model/Collection/Products.php to filter entity_id greater than 0, I was able to get the self-test to run much faster which makes me think that there’s something to the bug but possibly a way to work around this to allow for feed generation to work more efficiently.

Thanks!

**Comment by Marvin-Magmodules** [comment]
For future readers, issue was solved by adding the following to the env.php for the default database connection:

> 'initStatements' => 'SET NAMES utf8; SET optimizer_use_condition_selectivity=1;',

**Comment by dverkade** [comment]
Please look at the best practices for the optimizer_use_condition_selectivity setting on this page: https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/prerequisites/database-server/mysql.html
