### ISSUE TITLE
Orders Imported from Channable have cart rules applied

### ISSUE THREAD

**Issue by batmike** [magmodules/magento2-channable#110]
We have a cart price rule set up in Magento that doesn't have a code and so it auto-applies if the items match with the Actions rules when a customer puts them in their cart.

However, when orders are imported through Channable into our Magento shop, they seem to also be running through that logic and so the order prices in Magento don't match what was actually paid on the marketplace (Amazon, in this case).

Is there a setting or a way to have the imported orders bypass any cart pricing rules so that the prices paid on the marketplace are the ones that are also in the Magento order?

**Comment by Marvin-Magmodules** [comment]
HI @batmike, thank you for opening the issue. I've just pushed a fixed that unsets the discount amount on Channable orders. Can you try if this branch fixes your issue?

https://github.com/magmodules/magento2-channable/tree/bugfix/unset-discount

**Comment by Marvin-Magmodules** [comment]
HI @batmike, any update on this issue?

**Comment by batmike** [comment]
@Marvin-Magmodules - there have not been any more issues so the fix appears to be working properly. We also haven't seen any new issues pop up so we're in good working order. I'll close this but if anything new comes up, I'll certainly follow up again. Thanks!
