### ISSUE TITLE
[RFC] Add option to export category id's

### ISSUE THREAD

**Issue by Swahjak** [magmodules/magento2-channable#111]
Currently it's only possible to export categorie paths (and levels) based on https://github.com/magmodules/magento2-channable/blob/782cea9f29443a62af3360612c133c01886b73f0/Helper/Source.php#L781. But we have a case where we need (would like) the category ids of a product. Could this be added to the module?

**Comment by Marvin-Magmodules** [comment]
H @swahjak, thank you for the feature request. This will be added in the next release.

**Comment by Marvin-Magmodules** [comment]
Hi @Swahjak, just released version [1.4.23](https://github.com/magmodules/magento2-channable/releases/tag/1.4.23) with a fix for this issue. Category IDs can not be exported using the extra fields, see screenshot below. Closing this issue now but please feel free to reopen the issue if this still occurs. 
![chan](https://user-images.githubusercontent.com/20815641/114677426-95990780-9d0a-11eb-9f6f-72ceb0796aaa.png)

**Comment by samkooijman** [comment]
@Marvin-Magmodules You say "Category IDs can not be exported using the extra fields", but your comment is a bit contradictory. Could you please elaborate whether this is a typing error? In my point of view it is now possible to export category id's, however it is not 100% clear. Could you please confirm?

**Comment by Marvin-Magmodules** [comment]
Hi @samkooijman, ah yes sorry about this, was a typo indeed. It is NOW possible instead of NOT possible.
