### ISSUE TITLE
php 7.4 implode(): Passing glue string after array is deprecated

### ISSUE THREAD

**Issue by gunneman** [magmodules/magento2-channable#115]
A simple swap of the parameters should fix this error:
`Error for https://www.[domain].com/nl/channable/order/hook {"validated":"false","errors":"Deprecated Functionality: implode(): Passing glue string after array is deprecated. Swap the parameters in \/home\/[user]\/[domain]\/releases\/20210525094409\/vendor\/magmodules\/magento2-channable\/Model\/Order.php on line 519"}`

**Comment by Marvin-Magmodules** [comment]
Hi @gunneman, thank you for opening this issue. We have fixed this in [v1.5.1](https://github.com/magmodules/magento2-channable/releases/tag/1.5.1) and added linting of all PHP files in all supported versions to catch these issues in an earlier stage. Closing this issue now, but feel free to reopen if you still encounter this after the module update.
