### ISSUE TITLE
Schedule category is broken

### ISSUE THREAD

**Issue by evs-xsarus** [magmodules/magento2-channable#117]
On Magento 2.4.2-p1 commerce with Magento2-channable 1.5.1, it's not possible to schedule category changes.

The following is shown:
![image](https://user-images.githubusercontent.com/44158071/125452038-c23ce7de-d3bb-4dc2-86f6-218bc6611b5e.png)

But this popup is expected:

![image](https://user-images.githubusercontent.com/44158071/125452101-84597b52-c754-4dad-a9df-432cc2a9777c.png)

In the logs, we see:

Exception #0 (Magento\Framework\Exception\LocalizedException): The "componentType" configuration parameter is required for the "channable" component.
#1 Magento\Framework\View\Element\UiComponentFactory->mergeMetadataItem() called at [vendor/magento/framework/View/Element/UiComponentFactory.php:334]

Is this a known issue?

**Comment by Frank-Magmodules** [comment]
@evs-xsarus ,  
  
As we discussed through the mail this doesn't seem to be a Channable issue, can you let me know if we can close this issue or if you need any further help?

**Comment by evs-xsarus** [comment]
Can be closed .

**Comment by evs-xsarus** [comment]
@Frank-Magmodules turned out to be a missing file in the Channable module. Could you create a new release with:

magento/vendor/magmodules/magento2-channable/view/adminhtml/ui_component/catalogstaging_category_update_form.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Copyright © 2019 Magmodules.eu. All rights reserved.
 * See COPYING.txt for license details.
 */
-->
<form xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Ui:etc/ui_configuration.xsd">
    <fieldset name="channable">
        <argument name="data" xsi:type="array">
            <item name="config" xsi:type="array">
                <item name="label" xsi:type="string" translate="true">Channable</item>
                <item name="collapsible" xsi:type="boolean">true</item>
                <item name="sortOrder" xsi:type="number">100</item>
            </item>
        </argument>
        <field name="channable_cat_disable_export">
            <argument name="data" xsi:type="array">
                <item name="config" xsi:type="array">
                    <item name="sortOrder" xsi:type="number">1</item>
                    <item name="dataType" xsi:type="string">boolean</item>
                    <item name="formElement" xsi:type="string">checkbox</item>
                    <item name="prefer" xsi:type="string">toggle</item>
                    <item name="label" xsi:type="string" translate="true">Disable Category from export</item>
                    <item name="valueMap" xsi:type="array">
                        <item name="true" xsi:type="string">1</item>
                        <item name="false" xsi:type="string">0</item>
                    </item>
                    <item name="validation" xsi:type="array">
                        <item name="required-entry" xsi:type="boolean">false</item>
                    </item>
                    <item name="default" xsi:type="string">0</item>
                </item>
            </argument>
        </field>
    </fieldset>
</form>
```

PS Contents are the same as file magento/vendor/magmodules/magento2-channable/view/adminhtml/ui_component/category_form.xml

**Comment by CyberSecutor** [comment]
Thanx @evs-xsarus that fixed it for me as well

**Comment by Frank-Magmodules** [comment]
Great @evs-xsarus  and @CyberSecutor , we will add this into the upcoming release!

**Comment by Marvin-Magmodules** [comment]
Hi @evs-xsarus  and @CyberSecutor, thank you or the detailed issue report, solution and feedback. File has been added to the [1.5.3 release](https://github.com/magmodules/magento2-channable/releases/tag/1.5.3). Closing this issue now. Feel free to reopen the issue if this still occurs.
