### ISSUE TITLE
Improve performance of collection query in feed

### ISSUE THREAD

**Issue by bertterheide** [magmodules/magento2-channable#125]
The query to determine the product collection for a single page is terribly slow. This slowdown is caused by a suboptimal `ORDER BY` statement which results in the database having to use filesort.

**Comment by jorgb90** [comment]
Is this something to implement and improve collection?

**Comment by jorgb90** [comment]
@Marvin-Magmodules We applied this pull request and can confirm it gives performance improvement and works correctly.

**Comment by evs-xsarus** [comment]
@Marvin-Magmodules  when will this be in a release?

**Comment by Marvin-Magmodules** [comment]
@evs-xsarus in the current form not, as we don't see any positive performance impact on a vanilla installation. But we'll keep this open as we are refactoring this part at the moment for better performance.

**Comment by evs-xsarus** [comment]
FYI I've supplied the fix succesfully on a shop with ~65.000 products.
