### ISSUE TITLE
Extension issue 

### ISSUE THREAD

**Issue by world-of-walker** [magmodules/magento2-channable#129]
I installed this extension and i am using magento version : 2.4.2
extension version is 1.4.19. 

![image](https://user-images.githubusercontent.com/72004126/134170229-a4fefadf-5ac2-4bca-bbcd-a34502bd4230.png)
when i click on  these both links then my page is showing 404 error

**Comment by Marvin-Magmodules** [comment]
Hi @world-of-walker, this is hard to test from our side, can you please fill in our [support form](https://www.magmodules.eu/support-form.html) with (preferably staging/development) with (preferably staging/development) details of the environment so we can take a look with you on this issue?

**Comment by Marvin-Magmodules** [comment]
Closing the issue due to inactivity but feel free to reopen the issue if this still occurs.
