### ISSUE TITLE
Magento 2.2 upgrade - Serialized data

### ISSUE THREAD

**Issue by Tantuss** [magmodules/magento2-channable#13]
Upgrade to Magento 2.2 gives this error:
1 exception(s):
Exception #0 (InvalidArgumentException): Unable to unserialize value.

Exception #0 (InvalidArgumentException): Unable to unserialize value.
#0 vendor/magento/module-config/Model/Config/Backend/Serialized.php(55): Magento\Framework\Serialize\Serializer\Json->unserialize('a:357:{s:18:"_1...')
#1 vendor/magento/framework/Model/AbstractModel.php(601): Magento\Config\Model\Config\Backend\Serialized->_afterLoad()

The reason is that Magento changed their way serialized is stored in the database.
Before Magento 2.2, this was as serialized but from 2.2 is is like json_encoded.

See also:
http://devdocs.magento.com/guides/v2.2/ext-best-practices/tutorials/serialized-to-json-data-upgrade.html

**Comment by magmodules** [comment]
Hi, are you running v1.0.4 of the extension? As this version is compatible with v2.2

**Comment by magmodules** [comment]
Added extra checks in 1.0.5 for unserialized data fields. Please reopen issue if the problem still exists.
