### ISSUE TITLE
Missing link to order item in sales_order_tax_item

### ISSUE THREAD

**Issue by nocturnalfrog** [magmodules/magento2-channable#133]
Orders created through the channable Module are missing `item_id` data in the `sales_order_tax_item` table. 

(`item_id` refers to the `sales_order_item`.`item_id`)

**Comment by Marvin-Magmodules** [comment]
Hi @nocturnalfrog,

We are happy to share that we've just released the new [v1.12.0](https://github.com/magmodules/magento2-channable/releases/tag/1.12.0) version that fixes this issue! We are closing this issue now but please feel free to reopen the issue if this still occurs.
