### ISSUE TITLE
Question about the FeedUrl

### ISSUE THREAD

**Issue by joggienl** [magmodules/magento2-channable#136]
Hello,

I was looking into some help with the Channable Feed module.

- What are possible options for querystring params to pass to the URL? I know you can use `page=xx` to get the paged results. But are there more options?
- On website with multiple storeviews, and multiple (allowed) currencies per storeview.. how can we instruct the feedurl to give the result in the correct currency? For example, we want to feed both EUR and GBP for a specific storeview to channable.

Hope this question is a bit clear, if not let me know..!

**Comment by joggienl** [comment]
A little update to the question, we noticed that we could manipulate the required page by adding `page=xx` to the feed url. But we also learned that Channable in fact uses a construct via the path:

`http(s)://some-url/channable/feed/json/id/{storeId}/token/{token}/page/{page}`

This is a bit awkward but okay.

Besides the questions already asked, are there more path constructs like this?

**Comment by Marvin-Magmodules** [comment]
@joggienl, only one currency is supported per storeview. What is the use case for adding multiple currencies in the feed per storeview? About the params, only `page` and `pid` is supported, where pid is the product id that can be used to only limit 1 product.

**Comment by joggienl** [comment]
Hi @Marvin-Magmodules, thanks for the reply!

Thanks for the update on what params are supported. Is that documented somewhere?

About the currency, just like with `page` and `pid`, we would like to have a way to instruct the module to return the prices of the feed in a specific currency (like `currency=GBP`). As an example, we have an "en" (english) storeview that both supports EUR and GBP. In order to have the correct currency values on the advertisements it is wise to use the conversion that magento itself uses (correct = the same price that is visible on the product detail page). To be clear, we don't want multiple currencies in one request, but we want to import the feed url multiple times, based on the storeviews and currencies we support for that storeview.

Hope that this describes the situation a bit better, perhaps there is a more common way to do this but we have not found that yet 😅 . I noticed that people where adding separate JSON imports in Channable with a mapping of SKU and an (hand)converted price. Personally I do not think that this is a good manner to do so. Since we have the correct data in Magento I would prefer to use that as the source.

**Comment by Marvin-Magmodules** [comment]
Hi joggienl, clear, we've added this to the backlog.

**Comment by Marvin-Magmodules** [comment]
Hi @joggienl, we are happy to share we have added this feature in the [v1.10.0](https://github.com/magmodules/magento2-channable/releases/tag/1.10.0) release. The preview and json product feed urls now also accepts '/currency/xxx' so you can use different currencies. 

We are closing this issue now but please feel free to reopen the issue if this still occurs.
