### ISSUE TITLE
Speed up product feed

### ISSUE THREAD

**Issue by WalterSmulders** [magmodules/magento2-channable#137]
In Magmodules\Channable\Helper\Source::getProductFilters all visibility types will be added when: if (!empty($filters['relations'])) { this results in a very complex and slow query when Magmodules\Channable\Model\Generate::generateByStore calls getCollectionCountWithFilters.

When replacing:
array_push($filters['visibility'], Visibility::VISIBILITY_NOT_VISIBLE);
to:
$filters['visibility'] = array();
in Magmodules\Channable\Helper\Source the query gets processed a lot faster.

**Comment by Marvin-Magmodules** [comment]
HI @WalterSmulders,

Thank you for opening this issue, we are happy to share that we've just released the new [v1.6.2](https://github.com/magmodules/magento2-channable/releases/tag/1.6.2) version where we covered this issue. Thank you for the detailed issue report.

We are closing this issue now but please feel free to reopen the issue if this still occurs.
