### ISSUE TITLE
Bundles not in feed

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [magmodules/magento2-channable#14]
Hello,

We found out that bundles are not exported to the channable feed. If we look in the JSON or preview output the bundle id's are missing from the feed. After a peek in the code it looks like it is missing from the filters: [Source.php @ Line 351](https://github.com/magmodules/magento2-channable/blob/master/Helper/Source.php#L351) Is this a know issue?

**Comment by magmodules** [comment]
Hi Geoffrey, thanks for the notice and fixes. Bundle parents are now exported with min_price, price and max_price (v1.0.5: https://github.com/magmodules/magento2-channable/releases/tag/1.0.5)
