### ISSUE TITLE
GetOrderIdPrefix() returns bool

### ISSUE THREAD

**Issue by Wiseconn-SB** [magmodules/magento2-channable#141]
Version 1.6.0 / Magento version 2.3.7-p2
/vendor/magmodules/magento2-channable/Model/Config/System/OrderRepository.php line 157.

The order id prefix configuration returns a boolean instead of the saved string. This results in a 500 error.

**Comment by Marvin-Magmodules** [comment]
Hi @Wiseconn-SB, yes good catch, we have implemented the fix in [v1.6.1](https://github.com/magmodules/magento2-channable/releases/tag/1.6.1). Closing this issue now, but feel free to reopen if you still encounter this after the module update.
