### ISSUE TITLE
Dynamicly priced bundle products

### ISSUE THREAD

**Issue by Ahmet-Djedovic** [magmodules/magento2-channable#153]
**Describe the bug**
When a channable order comes to the magento system which contains a dynamic-price bundle. The bundle gets send thru as the price of the bundle.

If you for example add 5$ to the price in a rule at a sellers-platform. A product of 20$ becomes 25$. Then the order (which is a **bundle with dynamic price type**) get send to magento system. Turns from 25$ to the base price of 20$. This results in a mismatch in invoices. 

If you for example have a simple product and add 5$ to the price in a rule at a sellers-platform. A simple product of 15$ becomes 20$. Then a order of this product get send to magento system. And the invoice is good.

**Used versions**
- *Magento Version number*:Magento ver. 2.4.3-p1
- *Open source/Enterprise/B2b*: Open source
- *Channable module version number *:  V1.7.0

**To Reproduce**
1. Go to Magento admin panel and create a dynamic price bundle
2. Sync this product to channable
3. Add it to a platform of choice, example Bol.com.
4. Create a rule that states add 5$ to this  dynamic price bundle
5. Place a order on that product that has base price+5$
6. Wait for the order to get send to the Magento 2 system
7. See the price mismatch on the order. 
8. It removes the 5$ that has been added

**Expected behavior**
If you for example add 5$ to the price in a rule at a sellers-platform. A product of 20$ becomes 25$. Then the order (which is a **bundle with dynamic price type**) get send to magento system. And the invoice reads 25$ and the product is a dynamic priced bundle.

**Additional context**
Simple products work fine with price rule manipulation.

**Comment by Ahmet-Djedovic** [comment]
Any updates on this bug? @Frank-Magmodules

**Comment by Frank-Magmodules** [comment]
Hi @Ahmet-Djedovic ,

Thank you for your reaction here and sorry for the delayed response. It seems that this is a hard one to crack and get this correctly implemented without too much negative impact on performance. We'll look into this hopefully in the next release.

I appreciate your patience here!

**Comment by faicomb** [comment]
Any news @Frank-Magmodules?

**Comment by sanderjongsma** [comment]
I made a patch for this. When the order is created trough channable there is an extra check to see if product is a bundle. If this is true, dynamic calculations is disabled for the bundle and this ensures the price from channable is used.

Patch can be added to the `patches/magmodules/magento2-channable` directory and installed with: `vaimo/composer-patches`

```
@package magmodules/magento2-channable
@level 0

diff --git Service/Order/Items/Add.php Service/Order/Items/Add.php
index d96d3e6..bda85a5 100644
--- Service/Order/Items/Add.php
+++ Service/Order/Items/Add.php
@@ -7,8 +7,10 @@ declare(strict_types=1);

 namespace Magmodules\Channable\Service\Order\Items;

+use Magento\Bundle\Model\Product\Price;
 use Magento\Catalog\Api\Data\ProductInterface;
 use Magento\Catalog\Api\ProductRepositoryInterface;
+use Magento\Catalog\Model\Product\Type;
 use Magento\CatalogInventory\Api\StockRegistryInterface;
 use Magento\Checkout\Model\Session as CheckoutSession;
 use Magento\Framework\Exception\NoSuchEntityException;
@@ -112,6 +114,9 @@ class Add
                 $product = $this->getProductById((int)$item['id']);
                 $price = $this->getProductPrice($item, $product, $store, $quote);
                 $product = $this->setProductData($product, $price, $store, $lvbOrder);
+                if ($product->getTypeId() === Type::TYPE_BUNDLE) {
+                    $product->setPriceType(Price::PRICE_TYPE_FIXED);
+                }
                 $item = $quote->addProduct($product, (int)$item['quantity']);
                 $item->setOriginalCustomPrice($price);
                 $qty += (int)$item['quantity'];

```

**Comment by JonathanBBD** [comment]
Hi all,

I fixed it in my shop by changing this line
https://github.com/magmodules/magento2-channable/blob/3f87cf2713e4866a3a1f9d25c08b528b273abe75/Helper/Product.php#L937


Changed method `floatval` to `intval` due comparison with an Integer, this is always FALSE.
```diff
- if (floatval($product->getFinalPrice()) !== 0) {
+ if (intval($product->getFinalPrice()) !== 0) {
```

Result my facebook ad now uses the correct prices with dynamic bundle products.

**Comment by Ahmet-Djedovic** [comment]
@Frank-Magmodules 

This has been fixed. Thank you all.
