### ISSUE TITLE
Incorrect table definition; there can be only one auto column

### ISSUE THREAD

**Issue by SolsWebdesign** [magmodules/magento2-channable#157]
Hello I am happy to download the newest version of this module but am running into some errors: I get the error Area code is not set during setup:upgrade and some digging around gave me the following error:

Incorrect table definition; there can be only one auto column and it must be defined as a key, query was: ALTER TABLE `channable_returns` MODIFY COLUMN `id` bigint UNSIGNED NOT NULL  AUTO_INCREMENT COMMENT "Entity ID", MODIFY COLUMN `order_id` int UNSIGNED NOT NULL   COMMENT "Order ID", MODIFY COLUMN `channel_id` int UNSIGNED NOT NULL   COMMENT "Channel ID", ADD CONSTRAINT  PRIMARY KEY (`id`)

I had a look at the discriminating table and found the following:
```
<table name="channable_returns">
        <column name="entity_id"
                xsi:type="int"
                padding="20"
                identity="true"   // would the primary key
                nullable="false"
                unsigned="true"
                comment="Entity ID"
                onCreate="migrateDataFrom(id)" // nice
        />
...
<column name="id"  // the old id?
                xsi:type="int"
                padding="20"
                identity="false"  // so no longer the key
                nullable="false"
                unsigned="true"
                comment="Old ID"
        />
<constraint xsi:type="primary" referenceId="PRIMARY">
            <column name="entity_id"/> // defines the new key
        </constraint>

and in the previous version:
 <constraint xsi:type="primary" referenceId="PRIMARY">
            <column name="id"/>
        </constraint>
```

So my table had id as the primary key and now should have entity_id as the new key. But how do I unassign the old primary key? Magento seems to think it still is the primary key and simply wants to add a new primary key?

Could I be missing something? Or some command? Any help is appreciated :-)

**Comment by Marvin-Magmodules** [comment]
Hi @SolsWebdesign, thank you for opening this issue. We had to change the primary from `id` to `entity_id` in `channable_returns` table in v1.9.0. This will throw an issue if you try and downgrade the module to a previous version. 

Was this the case? If yes, you can remove the `entity_id` field in the `channable_returns` table  and rerun the setup:upgrade.

**Comment by SolsWebdesign** [comment]
Hi @Marvin-Magmodules thank you for your explanation and yes we tried to downgrade due to the area code is not set error. I am going to dig further because it is very well possible the "area code is not set" error is caused by one of the other modules that have been updated after running composer update. You can close this issue for now. Thank you for your quick reply!

**Comment by Marvin-Magmodules** [comment]
Hi @SolsWebdesign thank you for the quick reply, will close this issue now. But feel free to contact me on https://www.magmodules.eu/support-form.html to help dive into this issue so we can try and make sure this was not related to the Channable module.

**Comment by peterjaap** [comment]
We also ran into this issue but we didn't do a downgrade.

This is how we fixed it. Run this on the database before running `bin/magento set:up`:

```
ALTER TABLE `channable_returns` MODIFY COLUMN `entity_id` bigint(20) UNSIGNED NOT NULL;
ALTER TABLE `channable_returns` MODIFY COLUMN `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT;
```
