### ISSUE TITLE
bin/magento setup:db:status gives a false negative.

### ISSUE THREAD

**Issue by leonhelmus** [magmodules/magento2-channable#164]
Magento version 2.4.3-p2
php 7.4

When doing bin/magento setup:upgrade and after do a bin/magento setup:db:status.

**Expected**
* All modules are up to date.

**Actual**
Declarative Schema is not up to date
Run 'setup:upgrade' to update your DB schema and data.

**More Information**
Because of the db_schema.xml

```
    <table name="quote">
        <column name="transaction_fee"
                xsi:type="float"
                unsigned="true"
                nullable="false"
                comment="Transaction Fee"/>
    </table>

    <table name="sales_order">
        <column name="transaction_fee"
                xsi:type="float"
                unsigned="true"
                nullable="false"
                comment="Transaction Fee"/>
    </table>
```

Both have unsigned true Magento expects the float to have a scale/precision. Like float(10,2), because in the db_schema this is not declared. During bin/magento setup:db:status It needs to have a match in \Magento\Framework\Setup\Declaration\Schema\Db\MySQL\Definition\Columns\Real::fromDefinition otherwise unsigned is not registrated.

I have added this patch to resolve it.:

```
diff --git a/etc/db_schema.xml b/etc/db_schema.xml
--- a/etc/db_schema.xml
+++ b/etc/db_schema.xml
@@ -332,6 +332,8 @@
                 xsi:type="float"
                 unsigned="true"
                 nullable="false"
+                scale="2"
+                precision="10"
                 comment="Transaction Fee"/>
     </table>

@@ -340,6 +342,8 @@
                 xsi:type="float"
                 unsigned="true"
                 nullable="false"
+                scale="2"
+                precision="10"
                 comment="Transaction Fee"/>
     </table>
```

**Comment by Marvin-Magmodules** [comment]
Hi @leonhelmus,

We are happy to share that we've just released the new [1.10.1](https://github.com/magmodules/magento2-channable/releases/tag/1.10.1) version where we have fixed this issue. Thank you for opening this issue with detailed information on error entry point + suggestion on how to fix this!

We are closing this issue now but please feel free to reopen the issue if this still occurs.
