### ISSUE TITLE
Bol orders with specific return reason and no comment are not imported

### ISSUE THREAD

**Issue by 6Ways** [magmodules/magento2-channable#167]
When importing Returns from Bol.com and a customer fills in reason for return "Ik heb me bedacht" and leaves the comment field empty. The comment in the JSON response is NULL. Then the following error occurs and the order is not imported because this is no string.

main.CRITICAL: TypeError: Argument 1 passed to Magmodules\Channable\Model\Returns\DataModel::setComment() must be of the type string, null given, called in vendor/magmodules/magento2-channable/Service/Returns/ImportReturn.php on line 65 and defined in vendor/magmodules/magento2-channable/Model/Returns/DataModel.php:291

**Comment by Marvin-Magmodules** [comment]
Hi @6Ways 

We are happy to share that we've just released the new [1.10.2](https://github.com/magmodules/magento2-channable/releases/tag/1.10.2) version where we have fixed this issue. Thank you for opening this issue!

We are closing this issue now but please feel free to reopen the issue if this still occurs.
