### ISSUE TITLE
[REQUEST] Mangeto 2 MSI stock quantity by stock source export

### ISSUE THREAD

**Issue by Ylmzef** [magmodules/magento2-channable#172]
It would be nice to be able to see the product stock quantity according to MSI stock sources in Channable.

I want to configure rule for items from certain stock source but this is not possible at the moment.

For example, there may be items in a certain stock source that need to be sold faster, It can prioritize them using a RULE.

**Comment by Beagon** [comment]
Small bump because this could be really useful.

**Comment by Frank-Magmodules** [comment]
Hi There @Ylmzef , The moment has arrived! We've integrated this feature as an option within the latest release of the plugin. Please ensure you update to the latest version to access it. Thank you for raising this request. Now that it's implemented, I'm inclined to close it. However, if you have any concerns or feedback, please don't hesitate to share.
