### ISSUE TITLE
Company field required

### ISSUE THREAD

**Issue by JKingma** [magmodules/magento2-channable#173]
As JC-Electronics we're in the B2B market. So in our webshop, the Company field is required. This is an issue during the order import. For every import we get this error message:

> UnableToCreateOrderError(message='Please check the shipping address information. "company" is required. Enter and try again.'

As a workaround, we short change the Customer configuration, make the Company field "Optional", do another import and reset the Company field back to "Required".
On Ebay the company is not always filled (is it even there?). But wouldn't it be possible to set a default value (e.g. "-") for the Company field in case your Magento configuration requires it to be filled?

Used versions:
Magento ver. 2.4.3-p2
Open source/Enterprise/B2b: Enterprise with B2B
Channable v1.5.5 (will be updated soon)

**Comment by Marvin-Magmodules** [comment]
Hi @JKingma,

We are happy to share that we've just released the new [v1.12.0](https://github.com/magmodules/magento2-channable/releases/tag/1.12.0) version. On order import it will check if company is a required field and if yes it will replace empty company names with a dash. We are closing this issue now but please feel free to reopen the issue if this still occurs.
