### ISSUE TITLE
Unnecessary, but also missing indexes in table definition

### ISSUE THREAD

**Issue by markvds** [magmodules/magento2-channable#175]
Is it correct that some mistakes were made during composing the table indexes?

This index doesn't help much, giving that most probably the 'id' is already unique (table `channable_items`).
https://github.com/magmodules/magento2-channable/blob/4c0d22088ab054ca0e830ec3eb6ef2310fac41c8/etc/db_schema.xml#L65-L70

Then this (in table `channable_returns`). I can't even tell what the purpose of this index was supposed to be :confused: 
https://github.com/magmodules/magento2-channable/blob/4c0d22088ab054ca0e830ec3eb6ef2310fac41c8/etc/db_schema.xml#L99-L106

Then there are some missing, but important indexes:
- Table `channable_orders`, column `channable_id`. It's necessary for duplicate detection in [`createByDataArray()`](https://github.com/magmodules/magento2-channable/blob/4c0d22088ab054ca0e830ec3eb6ef2310fac41c8/Model/Order/Repository.php#L166).
- Table `channable_orders`, column `magento_order_id`. It's necessary for getting data in the grid update in [afterSave() of the Order DataModel](https://github.com/magmodules/magento2-channable/blob/4c0d22088ab054ca0e830ec3eb6ef2310fac41c8/Model/Order/DataModel.php#L399).
- I would create the same (`channable_id` and `magento_order_id`) indexes on the `channable_returns` table too, but a this moment they're not necessary because they don't get queried.

**Comment by Marvin-Magmodules** [comment]
Hi @markvds, thank you for the detailed issue description, we have just released the v1.12.0 version where we have implemented these changes. We are closing this issue now but please feel free to reopen the issue if this still occurs.
