### ISSUE TITLE
Qty increment no reflecting real value

### ISSUE THREAD

**Issue by Aquive** [magmodules/magento2-channable#182]
Magento version 2.3.6
Channable module version 1.4.20

I enabled Qty increments, but the qty in de feed does not reflect the amount filled in for a product. How can I solve this? Do I need to regenerate the feed somewhere? How would I do that?

**Comment by Marvin-Magmodules** [comment]
Hi @Aquive you can add this to the feed by selecting the `qty_increments` under Product Feed > Inventory Data > Fields (see image below). It should not change any qty field, only add the `qty_increments` to the product feed output. 

![Schermafbeelding 2022-11-07 om 10 36 59](https://user-images.githubusercontent.com/20815641/200277576-6ab05275-4bfa-42be-a1e0-46f5464df933.png)

**Comment by Aquive** [comment]
Thanks for your reply @Marvin-Magmodules I already did this to add it to the feed. It adds the field for every product with value 1 although some of them have another value, for instance 10. I checked different scopes, and they are not set. I seems the value is not output correctly to the feed.

**Comment by Marvin-Magmodules** [comment]
@Aquive, just tested this on two env's running the latest Channable version (v1.12.1), but I'm not able to break this. 

See e.g. the output of our demo env where product id 1 has a qty_increment set to 12:
https://demo.channable.magmodules.com/channable/feed/preview/id/1/token/1r7zcben990z0r1v6v4c3m7ulk0dit1x7ylfwy5hogfyltqk5xmajcjdpn90tyjc/no-cache/1667816198

Can you double check if there is no config option overwritten on strore view level?

**Comment by Aquive** [comment]
@Marvin-Magmodules thanks. Which config option do you mean? Which ones are relevant?

**Comment by Marvin-Magmodules** [comment]
@Aquive the two fields in the first screenshot (Enabled / Fields). Maybe they have different values on store view?

**Comment by Marvin-Magmodules** [comment]
Hi @Aquive, any update on this issue? If you need some additional support, we can check this for you by sharing some credentials of the admin through: https://www.magmodules.eu/support-form.html

**Comment by Aquive** [comment]
No, priorities shifted to other projects. I will reopen this issue when it is relevant (again). Thanks!
