### ISSUE TITLE
Order email to customer is not send for Channable orders

### ISSUE THREAD

**Issue by JKingma** [magmodules/magento2-channable#185]
In our Magento Commerce environment, the order confirmation email is not send when we receive an order through Channable.
Settings:
sales_email/order/enabled: Yes
magmodules_channable_marketplace/order/order_email: Yes
sales_email/general/async_sending: Enable

I have the feeling that because of the async sending of the order emails it is not working. There is a difference between how our normal orders are stored in the database versus how Channable orders are stored. 
Normal order (sales_order table):
![image](https://user-images.githubusercontent.com/9382705/202267585-a93f4ed7-8a01-4ca1-8007-c2fe3601d578.png)
Channable order:
![image](https://user-images.githubusercontent.com/9382705/202267628-720425d6-540f-4eef-a920-a9338b209a33.png)

According to this information: https://magento.stackexchange.com/questions/198779/how-does-asynchronous-email-sending-works-in-magento-2, the flag send_email should be 1 and not null as in the Channable order situation.

Used versions:
Magento ver. 2.4.4-p2
Open source/Enterprise/B2b: Enterprise with B2B
Channable v1.11.0 (will be updated soon)

**Comment by JKingma** [comment]
Anyone? @Marvin-Magmodules maybe?

**Comment by Frank-Magmodules** [comment]
HI @JKingma ,

Thank you for opening this issue! I'm happy to share that we are currently in the final stage of testing the new release where we have covered this for you. You can expect this new release at the beginning of next week, thanks for your patience!
