### ISSUE TITLE
Compatibility with two factor authentication

### ISSUE THREAD

**Issue by MajorKuprich** [magmodules/magento2-channable#188]
Hello,
Is this extension compatibile with 2FA Magento module?

**Comment by Marvin-Magmodules** [comment]
Hi @MajorKuprich, the module does not do anything with login validation, so I don't see how this can interfere in the workings of the module. Do you have any issues with this at the moment?

**Comment by MajorKuprich** [comment]
Hi @Marvin-Magmodules,
Thanks for the fast reply and clarification.
We are going to enable the 2FA module in Magento, we've wanted to know if this will cause problems with the Channable plugin.
So I close this topic.
