### ISSUE TITLE
Parent Product Stock Issue if Stock is Unmanaged

### ISSUE THREAD

**Issue by kaplansin** [magmodules/magento2-channable#192]
Channable feed generation checks cataloginventory_stock_item.is_in_stock for stock status of parent product.
But for Unmanaged stock Items it should also check manage_stock and use_config_manage_stock flags together.

For Unmanaged stock Items, magento is not updating is_in_stock value in cataloginventory_stock_item table. 
This can cause missing products in the feed.

\Magmodules\Channable\Helper\Product::validateProduct
```php
$filters = $config['filters'];
        if (!empty($parent)) {
            if (!empty($filters['stock'])) {
                if (!$parent->getIsInStock()) {
                    return false;
                }
            }
        }
```

**Comment by kaplansin** [comment]
https://github.com/magmodules/magento2-channable/pull/193

**Comment by Frank-Magmodules** [comment]
Thank you @kaplansin for your pull request on this.   
We are thrilled to announce that it has now been merged into our [latest release](https://github.com/magmodules/magento2-channable/releases/tag/1.14.1)!
