### ISSUE TITLE
Array to String conversion error while generating the feed

### ISSUE THREAD

**Issue by nwiegers01** [magmodules/magento2-channable#194]
Hi all,

Currently I am facing an issue while creating a new product feed. If I am trying to generate a new feed by going to **Configuration -> Channable -> Productfeed -> Preview** I am getting the following error.
_We can't generate the feed right now, please check the error log._

Once I open up the log it tells me that there is a Array to String conversion issue in **vendor/magmodules/magento2-channable/Helper/Product.php on line 832**.

Can this issue please be solved quickly ?

| Module            | Version  |
|-------------------|----------|
| Magento Version   | 2.4.5-P1 |
| PHP Version       | 8.1      |
| Channable Version | 1.14.0   |

**Comment by Marvin-Magmodules** [comment]
Hi @nwiegers01, thank you for opening this issue. We are unable to reproduce this issue, but looking at the code there is an attribute value that is returning an array instead of a string. 

Can you contact us though https://www.magmodules.eu/support-form.html to exchange some logins, so we check the current setup?

**Comment by nwiegers01** [comment]
Hi @Marvin-Magmodules ,

The environment setup is in the ticket. I am running the latest Magento version with the latest PHP version and also the latest version of the Channable module.

**Comment by nwiegers01** [comment]
Hi @Marvin-Magmodules ,

I just created a Magmodules support ticket ;)

**Comment by Frank-Magmodules** [comment]
Hi @nwiegers01 ,

Thank you for reaching out before. After reviewing your email, we were unable to replicate the issue you reported. However, we have added an additional verification in version [1.14.1](https://github.com/magmodules/magento2-channable/releases/tag/1.14.1) to address it. Could you please confirm if this update resolves the problem you were encountering?

**Comment by nwiegers01** [comment]
Hi @Frank-Magmodules ,

Yes it working as expected now!
