### ISSUE TITLE
Specify supported M2 version and PHP versions in readme

### ISSUE THREAD

**Issue by MrZoule** [magmodules/magento2-channable#198]
Hi,
In this PHP 8.1 migration momentum, it would be nice to specify in the readme wich M2 versions you support (2.4.5? 2.4.6?) and if PHP 8.1 (8.2?) is also supported.
Thank you

**Comment by Marvin-Magmodules** [comment]
Hi @MrZoule, yes this is good idea. Just added this: https://github.com/magmodules/magento2-channable#compatibility
We always include the Magento beta versions in our internal testing to make sure it is compatible on the day of release. Also added PHP 8.2 and Magento 2.4.6 to our CI flow: https://github.com/magmodules/magento2-channable/pull/199

We are closing this issue now but please feel free to reopen the issue if you encounter any issues.
