### ISSUE TITLE
bin/magento setup:upgrade causing an error

### ISSUE THREAD

**Issue by basselalaraaj** [magmodules/magento2-channable#20]
Magento version 2.1.9
PHP 7.0

When doing bin/magento setup:upgrade.

Im getting an error PHP Fatal error:  Cannot use Magento\Config\Model\ResourceModel\Config as Config because the name is already in use in /vagrant_data/score/httpdocs/vendor/magmodules/magento2-channable/Helper/General.php on line 13

![screen shot 2017-11-02 at 14 17 56](https://user-images.githubusercontent.com/5745279/32327970-a958a176-bfd8-11e7-9966-cbe4aa2c335a.png)

**Comment by magmodules** [comment]
Thnx, merged and pushed version 1.0.7
