### ISSUE TITLE
Out of stock product prices are not taken into account to the bundle product price

### ISSUE THREAD

**Issue by RemcoWolterink** [magmodules/magento2-channable#201]
When a bundle product in the product feed contains two products and one of the products is out of stock. The price of the complete bundle is decreasing to the price of the in-stock product.

**In-stock situation:**
Bundle price: 99,95
-- product 1: 49,95 (in stock)
-- product 2: 50,00 (in stock)

**Out of stock situation:**
Bundle price: 50,00
-- product 1: 49,95 (out of stock)
-- product 2: 50,00 (in stock)

Can you make a change that the price in the product feed will remain 99,95?

**Comment by RemcoWolterink** [comment]
Will do, but due to the holidays will be somewhere in January 2024.

**Comment by Frank-Magmodules** [comment]
Certainly, @RemcoWolterink , I'll leave this one open. Enjoy the holidays!

**Comment by RemcoWolterink** [comment]
@Frank-Magmodules didn't seem to solve the issue. I will ask my dev, to add some details from what he saw.

**Comment by sergiozt** [comment]
Hello @Frank-Magmodules 

We have updated the module to the latest version(1.16.0) and the issue still exists, can you please double check with the team the possible reason/fix?

**Comment by Frank-Magmodules** [comment]
Hello @sergiozt, could you kindly reach out to us [directly](https://www.magmodules.eu/help#:~:text=Got%20a%20plugin%20bug%20or%20an%20issue%3F) and provide the specific details of the product? Please include both the expected and actual results. While I'm unable to replicate the issue on my end, it's possible that there might be a discrepancy in the setup I'm using.
