### ISSUE TITLE
Feature request: Restore channel_id to sales_order table

### ISSUE THREAD

**Issue by jorgb90** [magmodules/magento2-channable#207]
Hi,

Is it possible to restore the functionality to also save the channel_name, channel_id and or channel_label back into the sales_order table? Its a request to support reporting functionalities and filtering in Magento, since it moved to its own table channable_orders this stopped working.

Thanks.

**Comment by Marvin-Magmodules** [comment]
Hi @jorgb90, can you elaborate a bit more about this? What kind of reporting are we talking about? We don't have any plans to restore this functionality as this data has been moved to `channable_orders` table.
