### ISSUE TITLE
Parent attributes not used by simple products

### ISSUE THREAD

**Issue by barryvdh** [magmodules/magento2-channable#208]
I have setup the Description field as fallback, but it doesn't show it:

![image](https://github.com/magmodules/magento2-channable/assets/973269/779f81c7-252d-4a72-b1f9-577207ea40e2)

![image](https://github.com/magmodules/magento2-channable/assets/973269/c4a9b234-b66e-4652-bb44-2a0a46deed39)

It keeps showing the simple version. Or does it only work when the simple variant is empty?

**Comment by Frank-Magmodules** [comment]
HI @barryvdh , We have attempted to replicate your issue using the same setup, but it appears that the simple product itself may be visible as a standalone product rather than being marked as "Not Visible Individually." I would be delighted to assist you with this matter. To proceed, kindly [provide us](https://www.magmodules.eu/help) with your details and a detailed description so we can investigate this issue together.

**Comment by barryvdh** [comment]
Thanks. It seems to work now.

But I cannot seem to get the Item Group ID to show in the feed, is there a guide for that? I need to link the simples to the parent in Amazon.

**Comment by Frank-Magmodules** [comment]
Hello, @barryvdh! I appreciate your reply. Can you confirm that the single product in question is set to "_Not Visible Individually"_ and is associated with only one active parent product? If this is the case, I would expect the "item_group_id" to be present in the JSON indeed. If you'd like to provide specific details, please don't hesitate to reach out to us [directly](https://www.magmodules.eu/help).

**Comment by barryvdh** [comment]
Hey @Frank-Magmodules 
The Simple product is set as Catalog only. We use a redirect for the simple to pre-select the configurable. I think this was needed for certain feeds. Can we get the group item without changing the visibility?

**Comment by Frank-Magmodules** [comment]
HI @barryvdh , no sorry, as then it's still a product that can be visible individually without being part of the group.

**Comment by Frank-Magmodules** [comment]
Hello @barryvdh, does the explanation above clarify why this issue occurred? I'd be more than happy to close the matter if it's clear now or give some more explanation on it where needed.

**Comment by Frank-Magmodules** [comment]
Hello @barryvdh , it appears that we haven't received any further information regarding this issue, and we consider it resolved for the time being. If it's still pertinent, please feel free to contact us directly or reopen the issue with additional details.
