### ISSUE TITLE
Division by zero. Service/Order/Shipping/CalculatePrice.php:75

### ISSUE THREAD

**Issue by yuriichayka** [magmodules/magento2-channable#219]
Version - 1.17.0
if the shipping price equals "0" - the error occurs
It wasn't the case in previous versions, happens due to recent modifications of the file

Example of the price request node:
    "price" => [
        "payment_method" => "amazon",
        "currency" => "GBP",
        "subtotal" => "83.64",
        "shipping" => "0",
        "total" => "83.64",
        "transaction_fee" => "0.00",
        "commission" => "0.00",
        "discount" => "0.00"
    ]
    
   Error:
    report.CRITICAL: DivisionByZeroError: Division by zero in /app/xxx/vendor/magmodules/magento2-channable/Service/Order/Shipping/CalculatePrice.php:75

**Comment by Frank-Magmodules** [comment]
Hello there @yuriichayka , we're happy to inform you that we've identified this issue and will include the fix in the next release. I'll leave the issue open for now and will confirm the release within this ticket at that time.

**Comment by Frank-Magmodules** [comment]
Hi There @yuriichayka , Thank you once more for bringing this issue to our attention and providing the necessary information. We're happy to inform you that we have addressed this matter in our [latest release](https://github.com/magmodules/magento2-channable/releases/tag/1.18.0)  I'm marking this issue as resolved for now. Please don't hesitate to reopen it if necessary. Thank you again for your cooperation!
