### ISSUE TITLE
Hyva Checkout: Call to undefined method Magento\Quote\Api\Data\AddressExtension::getChannablePickupLocation()

### ISSUE THREAD

**Issue by RickDBCN** [magmodules/magento2-channable#229]
Hi,

Our Hyva Checkout is giving the following error with the Channable module:
`#106 {main} {"exception":"[object] (Error(code: 0): Call to undefined method Magento\Quote\Api\Data\AddressExtension::getChannablePickupLocation() at /home/ubuntu/magento/vendor/magento/framework/Reflection/ExtensionAttributesProcessor.php:109)"} []`

Any idea what could cause this? We are not using any of the Channable shipping methods.

**Comment by Marvin-Magmodules** [comment]
Hi there @ RickDBCN, thank you for reaching out! 

When did this start to happen, after installation of the module or after an upgrade?

**Comment by RickDBCN** [comment]
> Hi there @RickDBCN, thank you for reaching out!
> 
> When did this start to happen, after installation of the module or after an upgrade?

Hi @Marvin-Magmodules, I believe after installation of the module. We've installed the module 2 weeks ago.
We just noticed these in the exception logs.

The method `getChannablePickupLocation()` is nowhere to be found in our project directory. How does this work and what could be the issue?
We are running 2.4.7.

**Comment by Marvin-Magmodules** [comment]
Hi @RickDBCN it's an extension attribute: https://github.com/magmodules/magento2-channable/blob/master/etc/extension_attributes.xml

All other commands were ran after installation, like setup:upgrade and If in production mode you recompiled?

**Comment by RickDBCN** [comment]
> Hi @RickDBCN it's an extension attribute: https://github.com/magmodules/magento2-channable/blob/master/etc/extension_attributes.xml
> 
> All other commands were ran after installation, like setup:upgrade and If in production mode you recompiled?

Ah, I see. Yes, we run all necessary commands after deployment and we recompile.

**Comment by RickDBCN** [comment]
Will do, thanks!

**Comment by arnoudhgz** [comment]
Thanks @Marvin-Magmodules  for the quick reply! We will investigate this further, could be that there was a hick-up in our compilation during deployment.
