### ISSUE TITLE
Channable: Orders & Items -> white page

### ISSUE THREAD

**Issue by Tantuss** [magmodules/magento2-channable#28]
With the latest Channable 1.0.12 + Magento 2.2.2
When opening the "Channable: Orders & Items", I get on my server a white page.

On my development environment, I get the follow error:

1 exception(s):
Exception #0 (Exception): Notice: Array to string conversion in vendor/magento/module-shipping/Model/Config/Source/Allmethods.php on line 61

Exception #0 (Exception): Notice: Array to string conversion in vendor/magento/module-shipping/Model/Config/Source/Allmethods.php on line 61
#0 vendor/magento/module-shipping/Model/Config/Source/Allmethods.php(61): Magento\Framework\App\ErrorHandler->handler(8, 'Array to string...', '/Users/jw/Proje...', 61, Array)
#1 vendor/magento/module-config/Model/Config/Structure/Element/Field.php(458): Magento\Shipping\Model\Config\Source\Allmethods->toOptionArray(false)
#2 vendor/magento/module-config/Model/Config/Structure/Element/Field.php(376): Magento\Config\Model\Config\Structure\Element\Field->_getOptionsFromSourceModel(Object(Magento\Shipping\Model\Config\Source\Allmethods))

---
Looking into this Magento code on this line:
'label' => '[' . $carrierCode . '] ' . $methodTitle,

At the $carrierCode = 'usps', I get an array returned.
This results in this error.
This carrier is actually not used.

**Comment by Marvin-Magmodules** [comment]
It's an issue in the Magento core class Allmethods (magento/module-shipping/Model/Config/Source/Allmethods.php): 

Exception #0 (Exception): Notice: Array to string conversion in vendor/magento/module-shipping/Model/Config/Source/Allmethods.php on line 61

Any new shipping methods installed?

**Comment by Tantuss** [comment]
No, it exist default from Magento and it is also not used.

**Comment by Tantuss** [comment]
I also reported it at Magento:
https://github.com/magento/magento2/issues/13136

But with them you need to wait quiet a long time till before a fix is released

**Comment by Tantuss** [comment]
See my ticket at Magento, but the real issue is here:
vendor/magento/module-usps/Model/Carrier.php
Line 1148: public function getAllowedMethods()

But that is also an Magento module.

**Comment by Marvin-Magmodules** [comment]
Closing this issue for now, as this is not an issue caused, nor can be fixed, by the channable module.
