### ISSUE TITLE
SImple product parent relation for groups product not working

### ISSUE THREAD

**Issue by martijnrmediact** [magmodules/magento2-channable#50]
We have a Magento Commerce 2.2.7 shop with the Channable 1.4.0 version. We have the configuration setup that for simple products that are part of a grouped product the parent grouped product url needs to be send to channable instead of the simple product url.

The above works for older products but new products since half a year are not having the grouped product url.

We looked into this and it seems its caused by the row_id and entity_id table data for products in the magento database.

The product link table is connected to the product row_id instead of the entity_id table and for newer products the row_id and entity_id table are not the same anymore. The code is linking parent products as entity_id instead of row_id. 

The expected result is that all simple products can make correct use of parent attributes.

**Comment by Frank-Magmodules** [comment]
Hi @martijnrmediact , seems I can't reproduce this on 2.3 with existing and/or new grouped products. Are these products created manually in the store or with an external import?

**Comment by martijnrmediact** [comment]
@Frank-Magmodules  thanx for the fast update. In Magento Commerce the entity_id and row_id are separate ids. What we now see that in a normal default magento installation the entity_id and row_id are the same but there can be action possible that they will be different. For example because of the use of content staging. I have added two screenshots one of the catalog_product_entity and one of the  catalog_product_link. Here you see that the product_id is matching the row_id instead of the entity_id.

The product_id with 1474 is still correct connected and has a correct link because this is one of the older products and here the row_id is the same as the entity id.

**Comment by Marvin-Magmodules** [comment]
Hi @martijnrmediact there is only one line of code we use to collect the parent id for the simple grouped product. See: https://github.com/magmodules/magento2-channable/blob/master/Helper/Product.php#L1104

If this has a different outcome than expected (unable to reproduce this on 2.3) I think the issue a broader than the Channable Module.

**Comment by martijnrmediact** [comment]
The function you mention is returning the product_id(s) that matches the parent product row_id maybe when loading the parent product collection it fetches based on entity_id?

**Comment by Marvin-Magmodules** [comment]
Yes think that is the issue, will to break this and get a fix implemented this week.
