### ISSUE TITLE
Feed broken after upgrade to 1.4.4

### ISSUE THREAD

**Issue by evs-xsarus** [magmodules/magento2-channable#53]
This change https://github.com/magmodules/magento2-channable/commit/947c4a19b7702b6255fb73e7f96c1bdc9a79f355#diff-5644b19765ce306fc588f975adb8f3bc breaks the feed for simple products in a configurable product. Image links are missing and the link to the product is incorrect.

Workaround is to stay on 1.4.3.

**Comment by Marvin-Magmodules** [comment]
This was caused by content staging in Magento Commerce. We have reverted the fix and added this as on option disabled by default. New release: [v1.4.5](https://github.com/magmodules/magento2-channable/releases/tag/1.4.5)

**Comment by evs-xsarus** [comment]
This version works correct. Tnx.
