### ISSUE TITLE
Missing requirements in composer.json

### ISSUE THREAD

**Issue by bjoern-flagbit** [magmodules/magento2-channable#56]
There are no requirements in your composer.json. 
Nothing about PHP version or Magento version.
This is sad guys.

**Comment by Marvin-Magmodules** [comment]
Minimum required Magento version has been added to the composer.json

**Comment by bjoern-flagbit** [comment]
Add the minimum PHP Version maybe also?

**Comment by Marvin-Magmodules** [comment]
Hi @bjoern-flagbit, It is not recommended to specify supported php versions in dependencies for Marketplace packages. We follow the Magento minimum php version's in this. 

See: https://github.com/magento/marketplace-tools/blob/master/validate_m2_package.php#L706
