### ISSUE TITLE
Not working together with Commerce B2B (shared catalog)

### ISSUE THREAD

**Issue by ruthgeridema** [magmodules/magento2-channable#65]
There is a problem at :
vendor/magmodules/magento2-channable/Model/Collection/Products.php

The following code defines the aliases as array keys (0,1,2.....). When the Shared Catalog module beforeLoad() plugin hits, it wants to use 0 as well.

`if (!empty($config['inventory']['attributes'])) {
            $collection->joinTable(
                'cataloginventory_stock_item',
                'product_id=entity_id',
                $config['inventory']['attributes']
            );
        }
`

The fix is simple, generate unique aliases like 'channable_qty' or 'channable_is_in_stock'.

QND fix for now so that the exporter works again:
`if (!empty($config['inventory']['attributes'])) {
            foreach($config['inventory']['attributes'] as $key => $value) {
                $config['inventory']['attributes'][$value] = $config['inventory']['attributes'][$key];
                unset($config['inventory']['attributes'][$key]);
            }
            $collection->joinTable(
                'cataloginventory_stock_item',
                'product_id=entity_id',
                $config['inventory']['attributes']
            );
        }`

**Comment by Marvin-Magmodules** [comment]
Hi @ruthgeridema thank you for the detailed issue report. Can you test if this branch fixed the issue (as we don't have Commerce B2B at hand atm): [commerce-b2b](https://github.com/magmodules/magento2-channable/tree/commerce-b2b)

Added the aliases to the join: https://github.com/magmodules/magento2-channable/commit/674c3da9c8437958f937f931948a360f4471cccf

**Comment by ruthgeridema** [comment]
Yes this works!
