### ISSUE TITLE
Missing products from configurables since 1.4.6.

### ISSUE THREAD

**Issue by marcoboom** [magmodules/magento2-channable#66]
Since we updated the extension to version 1.4.7, no configurable products will be added to the feed when the stock filter is enabled.

I think this is caused by a change in this commit:

[https://github.com/magmodules/magento2-channable/commit/464856ee7a837974edbc97a48e97884b1182e687#diff-653dbe4738abac6f25c4d1e94b4337cc](https://github.com/magmodules/magento2-channable/commit/464856ee7a837974edbc97a48e97884b1182e687#diff-653dbe4738abac6f25c4d1e94b4337cc)

Where in Helper/Product.php the line

```
if ($parent->getIsInStock() == 0) {
```

Is replace by

```
if ($parent->getIsSalable() && $parent->getIsInStock()) {
```

This means that a product where his parent is salable and has stock, the simple product cannot be validated.

Maybe it has to be:

```
if (!$parent->getIsSalable() || !$parent->getIsInStock()) {
```

**Comment by Marvin-Magmodules** [comment]
Hi @marcoboom thank you for the detailed error report. This was indeed an issue. Issue has been fixed and is implemented in [v1.4.7](https://github.com/magmodules/magento2-channable/releases/tag/1.4.8)
