### ISSUE TITLE
Order import not working with new M2 2.3.2 release

### ISSUE THREAD

**Issue by batmike** [magmodules/magento2-channable#69]
I was working through the 2.3.2 release and testing things out and, overall, there's nothing terribly breaking in there. There are some security fixes around the APIs which may have something to do with this and then there's some changes around orders too.

In any case, when I was making sure that orders from Channable were imported into Magento on 2.3.2 (using version 1.4.9 of the extension), the Channable dashboard reported a 302 error each time and the order failed to be imported. There was no log information either, so I'm not fully sure what the issue really is.

Let me know if there's anything I can test out on my end or any known information on this. Thanks!

**Comment by Marvin-Magmodules** [comment]
Hi @batmike, thank you for the issue report. We have reproduced this issue and the fix is being tested at this moment. We will be releasing a new version today to add support for Magento 2.3.2

**Comment by Marvin-Magmodules** [comment]
@batmike, just released a new version with the fix: [v1.4.10](https://github.com/magmodules/magento2-channable/releases/tag/1.4.10)

**Comment by batmike** [comment]
Thanks for the quick fix!
