### ISSUE TITLE
Feed Generation Slowdown from 1.4.6 onward

### ISSUE THREAD

**Issue by batmike** [magmodules/magento2-channable#71]
I'm using Magento Commerce and have tested this on 2.3.1 and 2.3.2. For versions of the extension 1.4.6 and up, our feed always times out. To fix this, I've been able to revert the following files to the 1.4.5 version:

Helper/Product.php
Model/Collection/Products.php
Model/Item.php

After that, the feed generates again after about a 30 second wait.

Our feed is heavily loaded with configurable products and contains about 32,000 in stock items that get passed to Channable.

Let me know if any more environment information would help to see what's causing this issue.

**Comment by Marvin-Magmodules** [comment]
Hi @batmike, thank you for the detailed issue report. Will do some investigation / debugging and will come back to you with the results. Can you send us some screenshots of the configuration settings of the module using our [contact form](https://www.magmodules.eu/contact-us.html).

**Comment by batmike** [comment]
@Marvin-Magmodules -

I just sent in the form with images of our Feed configuration section. Let me know if any further information would be helpful. Thanks!

**Comment by Marvin-Magmodules** [comment]
@batmike Just released a new version that has a fix for this issue. Please see [v1.4.11](https://github.com/magmodules/magento2-channable/releases/tag/1.4.11). Closing this issue now, but please feel free to reopen the issue if this problem still occurs. Thanks again for the detailed issue report.

**Comment by batmike** [comment]
@Marvin-Magmodules - Great - thanks for the update!
