### ISSUE TITLE
issue with async sales order grid update

### ISSUE THREAD

**Issue by fuess** [magmodules/magento2-channable#75]
Hi, when you enable Asynchronous Order Processing([link](https://devdocs.magento.com/guides/v2.3/performance-best-practices/configuration.html#asynchronous-order-data-processing)), the cron that takes care of this, raises an error:

`SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'channable_id' cannot be null, query was: INSERT  INTO `sales_order_grid` (`entity_id`,`status`,`store_id`,`store_name`,`customer_id`,`base_grand_total`,`base_total_paid`,`grand_total`,`total_paid`,`increment_id`,`base_currency_code`,`order_currency_code`,`shipping_name`,`billing_name`,`created_at`,`updated_at`,`billing_address`,`shipping_address`,`shipping_information`,`customer_email`,`customer_group`,`subtotal`,`shipping_and_handling`,`customer_name`,`payment_method`,`total_refunded`,`signifyd_guarantee_status`,`channable_id`,`channel_id`,`channel_name`,`channel_label`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON DUPLICATE KEY UPDATE `entity_id` = VALUES(`entity_id`), `status` = VALUES(`status`), `store_id` = VALUES(`store_id`), `store_name` = VALUES(`store_name`), `customer_id` = VALUES(`customer_id`), `base_grand_total` = VALUES(`base_grand_total`), `base_total_paid` = VALUES(`base_total_paid`), `grand_total` = VALUES(`grand_total`), `total_paid` = VALUES(`total_paid`), `increment_id` = VALUES(`increment_id`), `base_currency_code` = VALUES(`base_currency_code`), `order_currency_code` = VALUES(`order_currency_code`), `shipping_name` = VALUES(`shipping_name`), `billing_name` = VALUES(`billing_name`), `created_at` = VALUES(`created_at`), `updated_at` = VALUES(`updated_at`), `billing_address` = VALUES(`billing_address`), `shipping_address` = VALUES(`shipping_address`), `shipping_information` = VALUES(`shipping_information`), `customer_email` = VALUES(`customer_email`), `customer_group` = VALUES(`customer_group`), `subtotal` = VALUES(`subtotal`), `shipping_and_handling` = VALUES(`shipping_and_handling`), `customer_name` = VALUES(`customer_name`), `payment_method` = VALUES(`payment_method`), `total_refunded` = VALUES(`total_refunded`), `signifyd_guarantee_status` = VALUES(`signifyd_guarantee_status`), `channable_id` = VALUES(`channable_id`), `channel_id` = VALUES(`channel_id`), `channel_name` = VALUES(`channel_name`), `channel_label` = VALUES(`channel_label`)`.

This error is shown in the cron_schedule table for `job_code` `sales_grid_order_async_insert`.

At this moment I'm not sure if this is something you can fix or if this is a shortcoming of the async functionality.

**Comment by Frank-Magmodules** [comment]
Hi @fuess , thank you for the detailed issue report. We will try to reproduce this and update the issue once we have a solution for this.

**Comment by Marvin-Magmodules** [comment]
Hi @fuess, issue has been resolved in the [v1.4.12](https://github.com/magmodules/magento2-channable/releases/tag/1.4.12) release. Closing this issue now. Feel free to reopen the issue if this still occurs.
