### ISSUE TITLE
Not working with Magento MSI

### ISSUE THREAD

**Issue by jorgb90** [magmodules/magento2-channable#78]
We are using Magento's MSI and the stock availability and qty are Out of Stock and 0 for every product we have, which is of course not correct. Any idea?

**Comment by Frank-Magmodules** [comment]
HI @jorgb90 , Thank you for your message. Which exact Magento (CE or EE) and Channable version are you using that the moment? Did you've tried the use Salable QTY (experimental function) under the Advanced Options tab as well?

<img width="667" alt="Schermafbeelding 2019-08-22 om 15 18 43" src="https://user-images.githubusercontent.com/24823946/63517943-3e6c7080-c4f0-11e9-8362-36554afa1c8a.png">

**Comment by jorgb90** [comment]
Hi @Frank-Magmodules We are using Magento 2.3.2 and yes we have Use Salable QTY enabled.

**Comment by Frank-Magmodules** [comment]
Hi @jorgb90 ,

Strange, is there a possibility that you share more setup/store details so we can take a look with you on this issue? If so, please share these details safely through our [contact form.](https://www.magmodules.eu/contact-us.html)

Frank

**Comment by jorgb90** [comment]
@Frank-Magmodules 

I have send you an email with backend details

**Comment by Marvin-Magmodules** [comment]
Hi @jorgb90, thank you or the detailed issue report and logins. Issue has been resolved in the [v1.4.12](https://github.com/magmodules/magento2-channable/releases/tag/1.4.12) release. Closing this issue now. Feel free to reopen the issue if this still occurs.
