### ISSUE TITLE
InvendoryData class check for empty $config['inventory']['stock_id'] but doesn't exists

### ISSUE THREAD

**Issue by robbertstevens** [magmodules/magento2-channable#93]
The $config['inventory'] array only has the `attributes` key. This prefends use from using the Quantity attribute in the channable feed. Because it will always show it as "out of stock"

**Comment by Marvin-Magmodules** [comment]
Hi @robbertstevens, sorry for the late reply. The stock_id is only set when MSI is enabled. Is MSI enabled?

**Comment by robbertstevens** [comment]
No, we don't use inventory.

**Comment by Marvin-Magmodules** [comment]
And what version of Magento2 are you running?

**Comment by robbertstevens** [comment]
we run m2.3

**Comment by Marvin-Magmodules** [comment]
Hi @robbertstevens, looks like this issue fell off our radar, sorry for this. Is this stil the casing using the latest version? If yes, please contact us through our [contact form](https://www.magmodules.eu/support-form.html) with more information about your environment so we can help you out as we can not reproduce this issue.

**Comment by robbertstevens** [comment]
I don't think so, if it happens again I will make a new issue
