### ISSUE TITLE
Question: what is LVB?

### ISSUE THREAD

**Issue by arnoudhgz** [magmodules/magento2-channable#95]
This is not a real issue, but I did not know where else to go.... I'm looking into the release notes and code and I see quite some times `LVB`. What does it stand for?

**Comment by Marvin-Magmodules** [comment]
Hi @arnoudhgz, LVB stands for "Logistiek via Bol", see: https://www.bol.com/nl/m/logistiek/
When using this, stock movement is skipped when importing orders. If you have any additional questions, feel free to send us an email at: https://www.magmodules.eu/support-form.html
