### ISSUE TITLE
Orders imported from Channable don't have the currency that is set in channable.

### ISSUE THREAD

**Issue by Hexmage** [magmodules/magento2-channable#96]
When Channable orders are created in Magento the currency that was set in Channable isn't used in Magento, this is especially true if multiple countries are imported on the same storeview in Magento.

Eg. An order is created for a channable order of 1000 Norwegian krone but the order is created in Magento for 1000 euro because the storeviews default currency is euro. Even though the storeview allows NOK in a currency switcher.

Magmodules\Channable\Model\Order line 238:
`            $cart = $this->cartRepositoryInterface->get($cartId)->setStore($store)->setCurrency()->setIsSuperMode(true);`

I believe properly setting the currency on this line will fix this issue.

**Comment by Marvin-Magmodules** [comment]
Hi @Hexmage, thanks for the detailed issue report and PR. Just merged the PR and added to the [1.4.19](https://github.com/magmodules/magento2-channable/releases/tag/1.4.19)-release.

**Comment by webita** [comment]
HI, there is an update also for Magento 1 version? We have same problem but for The magento 1 version connector for channable.

**Comment by Frank-Magmodules** [comment]
Hi @webita , 
Thank you for opening and reporting this issue. Can you please share more details about your Magento 1 request through our [contact form.](https://www.magmodules.eu/support-form.html) so we can take a look with you on this and help you solve this issue? Thanks!
