### ISSUE TITLE
Cannot import order if minimum order amount is set/activated

### ISSUE THREAD

**Issue by JeroenVanLeusden** [magmodules/magento2-channable#99]
`\Magento\Quote\Model\Quote::validateMinimumAmount()`

**Comment by Marvin-Magmodules** [comment]
Hi @JeroenVanLeusden, thx for the PRs we will look into this end of the day.

**Comment by Marvin-Magmodules** [comment]
Hi @JeroenVanLeusden, thanks again for the PR, just merged and releases into [1.4.20](https://github.com/magmodules/magento2-channable/releases/tag/1.4.20)
